import type { Metadata } from "next"
import "@/styles/globals.css"
import "@/styles/markdown.css"
import "@/styles/style.css"
import AppContextProvider from "@/components/home/AppContext"
import EventContextProvider from "@/components/home/EventBusContext"

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
}

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<html lang="en">
			<body>
				<AppContextProvider>
					<EventContextProvider>{children}</EventContextProvider>
				</AppContextProvider>
			</body>
		</html>
	)
}
